export const DEV_INFORMATION_DATA = [
  {
    name: "Ariq Pradipa Santoso",
    photo: null,
    role: "Initiator / Frontend Developer",
    faculty: "F. Teknik",
    year: "2020",
    githubLink: null,
    websiteLink: "https://google.com",
    linkedinLink: "https://linkedin.com",
    team: "hive",
  },
  {
    name: "Muhammad Naufal Faza",
    photo: null,
    role: "Initiator / Backend Developer",
    faculty: "F. Teknik",
    year: "2020",
    githubLink: null,
    websiteLink: null,
    linkedinLink: "https://linkedin.com",
    team: "hive",
  },
  {
    name: "Aldi Naufal Fitrah",
    photo: null,
    role: "Product Manager",
    faculty: "F. Ilmu Komputer",
    year: "2019",
    githubLink: "http://github.com",
    websiteLink: "https://google.com",
    linkedinLink: null,
    team: "ristek",
  },
  {
    name: "Ariq Syahalam",
    photo: "/team/ariq_syahalam.png",
    role: "UI/UX Designer",
    faculty: "F. Ilmu Komputer",
    year: "2020",
    githubLink: "http://github.com",
    websiteLink: "https://google.com",
    linkedinLink: "https://linkedin.com",
    team: "ristek",
  },
  {
    name: "Rania Devina Nandini",
    photo: "/team/rania_devina.png",
    role: "Project Manager",
    faculty: "F. Ilmu Komputer",
    year: "2019",
    githubLink: "https://github.com",
    websiteLink: null,
    linkedinLink: "https://linkedin.com",
    team: "ristek",
  },
  {
    name: "Zuhal 'Alimul Hadi",
    photo: "/team/zuhal_hadi.png",
    role: "Frontend Developer",
    faculty: "F. Ilmu Komputer",
    year: "2020",
    githubLink: "https://github.com",
    websiteLink: "https://google.com",
    linkedinLink: "https://linkedin.com",
    team: "ristek",
  },
];
