export const DEV_INFORMATION_DATA = [
  {
    name: "Ariq Pradipa Santoso",
    photo: "/team/ariq_pradipa.png",
    role: "Initiator / Frontend Developer",
    faculty: "F. Teknik",
    year: "2020",
    githubLink: "https://github.com/ariqpradipa",
    websiteLink: null,
    linkedinLink: "https://www.linkedin.com/in/ariqpradipa/",
    team: "hive",
  },
  {
    name: "Muhammad Naufal Faza",
    photo: "/team/naufal_faza.png",
    role: "Initiator / Backend Developer",
    faculty: "F. Teknik",
    year: "2020",
    githubLink: "https://github.com/Gopalatius",
    websiteLink: null,
    linkedinLink: "https://www.linkedin.com/in/muhammad-naufal-faza/",
    team: "hive",
  },
  {
    name: "Zuhal 'Alimul Hadi",
    photo: "/team/zuhal_hadi.png",
    role: "Frontend Developer",
    faculty: "F. Ilmu Komputer",
    year: "2020",
    githubLink: "https://github.com/zuhalal",
    websiteLink: null,
    linkedinLink: "https://www.linkedin.com/in/zuhal-alimul-hadi/",
    team: "ristek",
  },
  {
    name: "Aldi Naufal Fitrah",
    photo: "/team/aldi_naufal.png",
    role: "Product Manager",
    faculty: "F. Ilmu Komputer",
    year: "2019",
    githubLink: null,
    websiteLink: null,
    linkedinLink: "https://www.linkedin.com/in/aldi-naufal-fitrah/",
    team: "ristek",
  },
  {
    name: "Ariq Syahalam",
    photo: "/team/ariq_syahalam.png",
    role: "UI/UX Designer",
    faculty: "F. Ilmu Komputer",
    year: "2020",
    githubLink: null,
    websiteLink: null,
    linkedinLink: "https://www.linkedin.com/in/ariqsyahalam/",
    team: "ristek",
  },
  {
    name: "Rania Devina Nandini",
    photo: "/team/rania_devina.png",
    role: "Project Manager",
    faculty: "F. Ilmu Komputer",
    year: "2019",
    githubLink: null,
    websiteLink: null,
    linkedinLink: "https://www.linkedin.com/in/rania-devina/",
    team: "ristek",
  },
];
